## $$Belajar Numpy$$


### 4. Indexing

In [3]:
import numpy as np

a = np.arange(5)**2
print('a = ',a)
print('Elemen pertama dari a adalah', a[0])
print('Elemen ke-4 dari a adalah', a[3])
print('Elemen terakhir dari a adalah', a[-1])

a =  [ 0  1  4  9 16]
Elemen pertama dari a adalah 0
Elemen ke-4 dari a adalah 9
Elemen terakhir dari a adalah 16


### 5. Slicing

In [6]:
import numpy as np

a = np.arange(5)**2
print('a = ',a)
print('Elemen dari 1-3 adalah ', a[0:3]) #[start:end), eksklusif
print('Elemen dari awal sampai 3 adalah ', a[:3])
print('Elemen dari 3 sampai akhir adalah ', a[3:])

a =  [ 0  1  4  9 16]
Elemen dari 1-3 adalah  [0 1 4]
Elemen dari awal sampai 3 adalah  [0 1 4]
Elemen dari 3 sampai akhir adalah  [ 9 16]


### 6. Iterasi

In [7]:
import numpy as np

a = np.arange(5)**2
for i in a:
    print('value = ',i)

value =  0
value =  1
value =  4
value =  9
value =  16


### 7. Perkalian Matriks

In [12]:
import numpy as np

a = np.array(([1,2,3],[4,5,6]))
b = np.ones((3,1))

hasil1 = np.dot(a,b)
hasil2 = a.dot(b) # cara lain

print('matriks a :')
print(a)
print('matriks b :')
print(b)
print('perkalian matriks a dan b =')
print(hasil1)

matriks a :
[[1 2 3]
 [4 5 6]]
matriks b :
[[1.]
 [1.]
 [1.]]
perkalian matriks a dan b =
[[ 6.]
 [15.]]


### 8. Manipulasi Matriks

In [19]:
import numpy as np

a = np.array(([1,2,3],[4,5,6]))

print('a :\n',a)
print('ukuran matriks a : ', a.shape)

# transpose matriks
print('\nTranspose matriks dari a:')
print(a.transpose())
print('ukuran matriks a : ', a.shape)
## cara lain : np.transpose(a)
## cara lain : a.T


# flatten matriks
print('\nFlatten matriks a:')
print(a.ravel())
print('ukuran matriks a : ', a.shape)
## cara lain : np.ravel(a)


# reshape matriks
print('\nReshape matriks a:')
print(a.reshape(3,2))
print('ukuran matriks a : ', a.shape)


# resize matriks
print('\nResize matriks a')
print(a.resize(3,2))
print('ukuran matriks a : ', a.shape)

a :
 [[1 2 3]
 [4 5 6]]
ukuran matriks a :  (2, 3)

Transpose matriks dari a:
[[1 4]
 [2 5]
 [3 6]]
ukuran matriks a :  (2, 3)

Flatten matriks a:
[1 2 3 4 5 6]
ukuran matriks a :  (2, 3)

Reshape matriks a:
[[1 2]
 [3 4]
 [5 6]]
ukuran matriks a :  (2, 3)

Resize matriks a
None
ukuran matriks a :  (3, 2)
