### 1. Membuat numpy array

In [33]:
import numpy as np

# membuat vector
a = np.array([1,2,3,4])
b = np.array([10.2, 3.1, 1.2, 9.4])

# membuat vector dengan range(batas bawah, batas atas, loncat)
c = np.arange(0,8,2)

# membuat linspace(batas bawah, batas atas, jumlah bagian)
d = np.linspace(1,10,4)


# display
print('himpunan a = ',a)
print('himpunan b = ',b)
print('himpunan c = ',c)
print('himpunan d = ',d)

himpunan a =  [1 2 3 4]
himpunan b =  [10.2  3.1  1.2  9.4]
himpunan c =  [0 2 4 6]
himpunan d =  [ 1.  4.  7. 10.]


### 2. Membuat Matriks

In [36]:
import numpy as np

# membuat multidimensi atau matrix
e = np.array([(2,3,4,5,6),(4,5,6,7,8)])

# matrix dengan nilai nol
f = np.zeros((2,4))

# matrix dengan nilai satu
g = np.ones((2,4))

#matix identitas
h = np.identity(3)
i = np.eye(4)

#display
print('matrix e = ')
print(e)
print('matrix f = ')
print(f)
print('matrix g = ')
print(g)
print('matrix h = ')
print(h)
print('matrix i = ')
print(i)

matrix e = 
[[2 3 4 5 6]
 [4 5 6 7 8]]
matrix f = 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
matrix g = 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
matrix h = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
matrix i = 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 3. Operasi Aritmatika Himpunan

In [51]:
import numpy as np

# list python
a = [1,2,3]
b = [4,5,6]

# array numpy
anp = np.array([1,2,3])
bnp = np.array([4,5,6])

# penjumlahan
print('Penjumlahan (perhatikan perbedaannya)')
print(' Penjumlahan list python: a + b = ', a + b)
print(' Penjumlahan himpunan numpy: anp + bnp = ', anp + bnp)

# pengurangan
print('\nPengurangan \n anp - bnp = ', anp - bnp)

# perkalian
print('\nPerkalian\n anp x bnp = ', anp*bnp)

# pembagian
print('\nPembagian\n anp : bnp = ', anp/bnp)

Penjumlahan (perhatikan perbedaannya)
 Penjumlahan list python: a + b =  [1, 2, 3, 4, 5, 6]
 Penjumlahan himpunan numpy: anp + bnp =  [5 7 9]

Pengurangan 
 anp - bnp =  [-3 -3 -3]

Perkalian
 anp x bnp =  [ 4 10 18]

Pembagian
 anp : bnp =  [0.25 0.4  0.5 ]
