
### 9. Stacking Matriks

In [4]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])


# stacking (menumpuk)
print('a: ',a)
print('b: ',b)
print('menumpuk mendatar a dan b:\n', np.hstack((a,b)))
print('menumpuk vertikal a dan b:\n', np.vstack((a,b)))

c = np.ones((2,2))
d = np.zeros((2,2))
print('\nc:\n',c)
print('d:\n',d)
print('horizontal stacking matrix c dan d:\n', np.hstack((c,d)))
print('vertikal stacking matrix c dan d:\n', np.vstack((c,d)))

a:  [1 2 3]
b:  [4 5 6]
menumpuk mendatar a dan b:
 [1 2 3 4 5 6]
menumpuk vertikal a dan b:
 [[1 2 3]
 [4 5 6]]

c:
 [[1. 1.]
 [1. 1.]]
d:
 [[0. 0.]
 [0. 0.]]
horizontal stacking matrix c dan d:
 [[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
vertikal stacking matrix c dan d:
 [[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]


### 10. Cara advance buat array dan matriks

In [7]:
import numpy as np

# buat matriks dengan type data tertentu
a = np.array(([1,2,3],[4,5,6]), dtype = float)


# membuat array menggunakan function
def kuadrat(baris,kolom):
    return kolom**2

def jumlah(baris,kolom):
    return (kolom+baris)

b = np.fromfunction(kuadrat, (1,10), dtype = int) # (fungsi, ukuran matriks, tipe)

c = np.fromfunction(jumlah, (3,3), dtype = int)


# membut array atau matriks menggunakan iterasi
iterasi = (x for x in range(4))
d = np.fromiter(iterasi, dtype = int)

# multiple array
dtype = [('nama','S100'),('tinggi', int)]
data = [('adi', 165),('dia', 150),('ida', 160)]
e = np.array(data, dtype)

# display
print('a:\n',a)
print('b:', b)
print('c:\n', c)
print('d:', d)
print('e:', e)

a:
 [[1. 2. 3.]
 [4. 5. 6.]]
b: [[ 0  1  4  9 16 25 36 49 64 81]]
c:
 [[0 1 2]
 [1 2 3]
 [2 3 4]]
d: [0 1 2 3]
e: [(b'adi', 165) (b'dia', 150) (b'ida', 160)]


### 11. Statistik

In [10]:
# membuat data
dtype = [('nama','S100'),('tinggi', int)]
data = [('adi', 165),('ida', 150),('dia', 160)]
a = np.array(data, dtype)

# sorting data berdasarkan tinggi
print(np.sort(a, order='tinggi'))

# sorting data berdasarkan nama
print(np.sort(a, order='nama'))

[(b'ida', 150) (b'dia', 160) (b'adi', 165)]
[(b'adi', 165) (b'dia', 160) (b'ida', 150)]


In [17]:
# membuat data random dan dibulatkan
a = np.floor(np.random.randn(5)*10)

# statistik
print('data:',a)
print('nilai max dari data:', a.max())
print('nilai min dari data:', a.min())
print('posisi max dari data:', a.argmax()+1)

data: [-7. -5. -9. -4.  1.]
nilai max dari data: 1.0
nilai min dari data: -9.0
posisi max dari data: 5
